# -*- coding: utf-8 -*-

# LoginScreen implementation generated from reading ui file 'LoginScreenUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# __all__ = ['LoginScreenUI']

class LoginUI(object):
    def setupUi(self, LoginScreen):
        #* <----------   LoginScreen is the main window that must be closed to close the program    ---------->
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(650, 460)
        #* <----------    Set the window to be in the center of the screen and hide the main window (only display the main widget)    ---------->
        LoginScreen.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        LoginScreen.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        LoginScreen.setWindowTitle("Master Panel")

        self.widget = QtWidgets.QWidget(LoginScreen)
        self.widget.setWindowTitle("Login Panel")
        self.widget.setGeometry(QtCore.QRect(40, 40, 600, 410))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")


        self.MasterPanel = QtWidgets.QLabel(self.widget)
        self.MasterPanel.setGeometry(QtCore.QRect(290, 40, 270, 330))
        self.MasterPanel.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"border-radius: 10px;")
        self.MasterPanel.setText("")
        self.MasterPanel.setObjectName("MasterPanel")


        self.StylePanel = QtWidgets.QLabel(self.widget)
        self.StylePanel.setGeometry(QtCore.QRect(40, 25, 270, 360))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StylePanel.setFont(font)
        self.StylePanel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-radius: 10px;")
        self.StylePanel.setText("")
        self.StylePanel.setObjectName("StylePanel")


        self.loginLabel = QtWidgets.QLabel(self.widget)
        self.loginLabel.setGeometry(QtCore.QRect(330, 60, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: rgba(0, 0, 0,200);")
        self.loginLabel.setObjectName("loginLabel")


        self.usernameLabel = QtWidgets.QLineEdit(self.widget)
        self.usernameLabel.setGeometry(QtCore.QRect(330, 140, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 7px;")
        self.usernameLabel.setMaxLength(25)
        self.usernameLabel.setClearButtonEnabled(False)
        self.usernameLabel.setObjectName("usernameLabel")


        self.passwordLabel = QtWidgets.QLineEdit(self.widget)
        self.passwordLabel.setGeometry(QtCore.QRect(330, 200, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 7px;")
        self.passwordLabel.setMaxLength(25)
        self.passwordLabel.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLabel.setObjectName("passwordLabel")


        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setGeometry(QtCore.QRect(330, 270, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton#loginButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(200,200,200,255);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#loginButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: rgba(205,107, 107,255);\n"
"    baclground-position: calc(100% - 10px)center;\n"
"}\n"
"QPushButton#loginButton:hover{\n"
"    background-color: rgba(255,107,107,255);\n"
"}")
        self.loginButton.setFlat(False)
        self.loginButton.setObjectName("loginButton")
        self.forgetButton = QtWidgets.QPushButton(self.widget)
        self.forgetButton.setGeometry(QtCore.QRect(330, 320, 201, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.forgetButton.setFont(font)
        self.forgetButton.setAutoFillBackground(False)
        self.forgetButton.setStyleSheet("QPushButton#forgetButton{\n"
"    color: rgba(85,98,112,255);\n"
"    background-color: rgba(255,255,255, 255);\n"
"    border-radius: 5px;    \n"
"    border-color: rgba(255,255,255,255);\n"
"}\n"
"QPushButton#forgetButton:pressed{\n"
"    color: rgb(205,107, 107);\n"
"}\n"
"QPushButton#forgetButton:hover{\n"
"    color: rgb(65, 163, 176);\n"
"}\n"
"")
        self.forgetButton.setAutoDefault(False)
        self.forgetButton.setObjectName("forgetButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 50, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.StyleIcon = QtWidgets.QLabel(self.widget)
        self.StyleIcon.setGeometry(QtCore.QRect(50, 210, 261, 211))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(150)
        self.StyleIcon.setFont(font)
        self.StyleIcon.setStyleSheet("color: rgba(255, 107, 107, 255);")
        self.StyleIcon.setObjectName("StyleIcon")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.clicked.connect(self.CloseUI)
        self.exitButton.setGeometry(QtCore.QRect(520, 50, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton#exitButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(85,98,112,255);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#exitButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: rgba(205,107, 107,255);\n"
"    baclground-position: calc(100% - 10px)center;\n"
"}\n"
"QPushButton#exitButton:hover{\n"
"    background-color: rgba(255,107,107,255);\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.naccButton = QtWidgets.QPushButton(self.widget)
        self.naccButton.setGeometry(QtCore.QRect(400, 340, 75, 23))
        self.naccButton.setStyleSheet("QPushButton#naccButton{\n"
"    color: rgba(85,98,112,255);\n"
"    background-color: rgba(255,255,255, 255);\n"
"    border-radius: 5px;    \n"
"    border-color: rgba(255,255,255,255);\n"
"}\n"
"QPushButton#naccButton:pressed{\n"
"    color: rgb(205,107, 107);\n"
"}\n"
"QPushButton#naccButton:hover{\n"
"    color: rgb(65, 163, 176);\n"
"}")
        self.naccButton.setObjectName("naccButton")


        #TODO: Adding blur and shades to labels and buttons
        self.loginButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=5, xOffset=0, yOffset=0))
        self.widget.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=10, xOffset=0, yOffset=0))

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "LoginScreen"))
        self.loginLabel.setText(_translate("LoginScreen", "Log In"))
        self.usernameLabel.setPlaceholderText(_translate("LoginScreen", "Username"))
        self.passwordLabel.setPlaceholderText(_translate("LoginScreen", "Password"))
        self.loginButton.setText(_translate("LoginScreen", "Log In"))
        self.forgetButton.setText(_translate("LoginScreen", "Forget Password or username"))
        self.label.setText(_translate("LoginScreen", "Welcome"))
        self.StyleIcon.setText(_translate("LoginScreen", "­"))
        self.label_4.setText(_translate("LoginScreen", "to my DataBase"))
        self.exitButton.setText(_translate("LoginScreen", "❌"))
        self.naccButton.setText(_translate("LoginScreen", "New account"))

    def CloseUI(self):
        self.widget.destroy(True)
        sys.exit()      

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        LoginScreen = QtWidgets.QWidget()
        ui = LoginUI()
        ui.setupUi(LoginScreen)
        LoginScreen.show()
        sys.exit(app.exec_())